---
- hosts: all
  #remote_user: ubuntu
  become: false
  #become_method: sudo
  become_method: runas
  gather_facts: yes
  tasks:

 

#*********7zip Installation*****************************
    - name: create directory on localhost
      file:
        path: /tmp/ansible
        state: directory
      delegate_to: localhost

 

    - name: download 7zip from url
      get_url:
        url: http://7-zip.org/a/7z1604-x64.msi
        dest: /tmp/ansible
      delegate_to: localhost

 

    - name: create directory
      win_file:
        path: C:\ansible
        state: directory

 

    - name: copy 7zip from localhost to windows server
      win_copy:
        src: /tmp/ansible/7z1604-x64.msi
        dest: C:\ansible\7z1604-x64.msi

 

    - name: install 7 zip
      win_package:
        path: 'C:\ansible\7z1604-x64.msi'
        state: present
#*********Anydesk Installation**************************
    - name: create directory on localhost
      file:
        path: /tmp/anydesk
        state: directory
      delegate_to: localhost
    - name: download AnyDesk from url
      get_url:
        url: https://download.anydesk.com/AnyDesk.msi
        dest: /tmp/ansible/
      delegate_to: localhost
    - name: create directory
      win_file:
        path: C:\ansible\
        state: directory
    - name: copy AnyDesk from localhost to windows server
      win_copy:
        src: /tmp/ansible/AnyDesk.msi
        dest: C:\ansible\AnyDesk.msi
    - name: install AnyDesk
      win_package:
        path: C:\ansible\AnyDesk.msi
        state: present
